import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Playfair_Display, Lato, Poppins } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { BookingProvider } from "@/components/context-provider";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-playfair",
});
const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${lato.variable} ${poppins.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
          <BookingProvider>
            <div className="min-h-screen flex flex-col">
              <Navbar />
              {children}
              <Footer />
            </div>
          </BookingProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
