import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { Playfair_Display, Lato } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { ContextProvider } from "@/components/context-provider";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
});
const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${playfair.variable} ${lato.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <ContextProvider>
            <div className="min-h-screen flex flex-col">
              <Navbar />
              {children}
              <Footer />
            </div>
          </ContextProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
